# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="The Mythical Person Month is a modernized version of the Mythical Man Month book."
REPO_LICENSE=""
REPO_TOPICS="book,gender-fair-language,inclusion,project-management"

# URLs section
REPO_GIT_SSH="git@github.com:chicks-net/mythical_person_month.git"
REPO_WEB_URL="https://github.com/chicks-net/mythical_person_month"

# Derived values
REPO_ORG_NAME="chicks-net"
REPO_REPO_NAME="mythical_person_month"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="false"
FLAG_CLAUDE_REVIEW="false"
FLAG_COPILOT_REVIEW="false"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "book"
    "gender-fair-language"
    "inclusion"
    "project-management"
)
