# .repo.toml

[about]
description = "The Mythical Person Month is a modernized version of the Mythical Man Month book."
topics = ["book", "gender-fair-language", "inclusion", "project-management"]

[urls]
git_ssh = "git@github.com:chicks-net/mythical_person_month.git"
web_url = "https://github.com/chicks-net/mythical_person_month"

[flags]
claude = true
claude-review = true
copilot-review = true
standard-release = true
